apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-legacy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-legacy-app
  template:
    metadata:
      labels:
        app: poc-legacy-app
    spec:
      containers:
        - name: app
          image: poc-legacy-app:latest
          ports:
            - containerPort: 8080
